#!/bin/bash

# config
#	BASH_DEF_{COLOUR,GIT,PREFIX,TITLE}={yes,no}

# generate prompt and title dynamically from
#	hostname
#	git status
#	cwd
#	date/time
#	command
#	return status

source ~/bin/function.d/parse_git_branch.sh
source ~/bin/function.d/title.sh

unset PROMPT_DIR
unset PROMPT_GIT
unset PROMPT_GIT_COLOUR
unset PROMPT_PREFIX
unset PROMPT_PREFIX_COLOUR
unset PROMPT_SUFFIX

# Set some defaults
[[   $USER     != flatcap                             ]] && BASH_DEF_PREFIX=yes
[[   $HOSTNAME != rich.flatcap.org                    ]] && BASH_DEF_COLOUR=yes
[[ ! $TERM     =~ ^(xterm|vt100|linux)$               ]] && BASH_DEF_COLOUR=no
[[ ! $TERM     =~ ^(xterm|vt100)$                     ]] && BASH_DEF_TITLE=no
[[   $HOSTNAME =~ ^(muse.flatcap.org|www.russon.org)$ ]] && BASH_DEF_GIT=yes 
[[   $SSH_CLIENT                                      ]] && BASH_DEF_PREFIX=yes

# --------------------------------------------------------------------

if [[ $BASH_DEF_PREFIX == yes ]]; then
	if [ $USER = "root" ]; then
		PROMPT_PREFIX="#"
	else
		PROMPT_PREFIX=${USER^^}
		PROMPT_PREFIX="${PROMPT_PREFIX:0:1}"
	fi
	PROMPT_PREFIX="[$PROMPT_PREFIX]"
fi

# --------------------------------------------------------------------

PROMPT_PREFIX_COLOUR="$PROMPT_PREFIX"
if [[ $BASH_DEF_COLOUR == yes ]]; then
	case $HOSTNAME in
		rich.flatcap.org)	PROMPT_COLOUR=32 ;;	# green
		www.russon.org)		PROMPT_COLOUR=31 ;;	# red
		derwent)		PROMPT_COLOUR=33 ;;	# yellow
		enigma.flatcap.org)	PROMPT_COLOUR=36 ;;	# cyan
		*)			PROMPT_COLOUR=35 ;;	# magenta
	esac
	if [ -n "$PROMPT_PREFIX" ]; then
		PROMPT_PREFIX_COLOUR="\e[${PROMPT_COLOUR}m${PROMPT_PREFIX}\e[0m"
	fi
fi

# --------------------------------------------------------------------

PROMPT_DIR="${PWD/#$HOME/~}"

# --------------------------------------------------------------------

if [[ $BASH_DEF_GIT == yes ]]; then
	PROMPT_GIT="$(parse_git_branch)"
	if [ -n "$PROMPT_GIT" ]; then
		PROMPT_GIT="($PROMPT_GIT)"
		PROMPT_GIT_COLOUR=$PROMPT_GIT
		if [[ $BASH_DEF_COLOUR == yes ]]; then
			PROMPT_GIT_COLOUR="\e[38;5;237m$PROMPT_GIT\e[0m"
		fi
	fi
fi

# --------------------------------------------------------------------

if [[ $UID == 0 ]]; then
	PROMPT_SUFFIX="# "
else
	PROMPT_SUFFIX="$ "
fi

# --------------------------------------------------------------------

if [[ $BASH_DEF_TITLE == yes ]]; then
	title "$PROMPT_PREFIX $PROMPT_DIR$PROMPT_GIT"
fi

# --------------------------------------------------------------------

echo -en "$PROMPT_PREFIX_COLOUR$PROMPT_DIR$PROMPT_GIT_COLOUR$PROMPT_SUFFIX"

