#!/bin/bash
#
# config
#	BASH_DEF_{COLOUR,GIT,PREFIX,TITLE}={yes,no}

PS1=""
if [[ $BASH_DEF_PREFIX == yes || ( ! $BASH_DEF_PREFIX && $SSH_CLIENT ) ]]; then
	if [ $USER = "root" ]; then
		PROMPT_PREFIX="#"
	else
		PROMPT_PREFIX=${USER^^}
		PROMPT_PREFIX="${PROMPT_PREFIX:0:1}"
	fi
	PS1="[$PROMPT_PREFIX]"
fi

if [[ $BASH_DEF_COLOUR == yes || ( ! $BASH_DEF_COLOUR && $TERM =~ ^(xterm|linux|vt100)$ ) ]]; then
	case $HOSTNAME in
		muse.flatcap.org)	PROMPT_COLOUR=32 ;;	# green
		www.russon.org)		PROMPT_COLOUR=31 ;;	# red
		derwent)		PROMPT_COLOUR=33 ;;	# yellow
		enigma.flatcap.org)	PROMPT_COLOUR=36 ;;	# cyan
		*)			PROMPT_COLOUR=35 ;;	# magenta
	esac
	if [ -n "$PS1" ]; then
		PS1="\e[${PROMPT_COLOUR}m${PS1}\e[0m"
	fi
fi

PS1="${PS1}\\w"

if [[ $BASH_DEF_GIT == yes || ( ! $BASH_DEF_GIT && $HOSTNAME =~ ^(muse.flatcap.org|www.russon.org)$ ) ]]; then
	PS1="${PS1}\$(parse_git_branch)"
fi

PS1="${PS1}\\$ "

if [[ $BASH_DEF_TITLE == yes || ( ! $BASH_DEF_TITLE && $TERM =~ ^(xterm|vt100)$ ) ]]; then
	PROMPT_COMMAND='echo -ne "\017\e]0;${PWD/#$HOME/~}\a"'
else
	PROMPT_COMMAND='echo -ne "\017"'
fi

export PS1
export PROMPT_COMMAND
export PROMPT_COLOUR
export PROMPT_PREFIX

