[ -f ~/.bash_config ] && source ~/.bash_config

umask 0007

unset MAILCHECK

shopt -s cdspell
shopt -s extglob
shopt -s histappend
shopt -s histreedit
shopt -s histverify
shopt -s progcomp

unalias -a
for dir in env function complete alias; do
	[ -d $HOME/bin/$dir/ ] || continue;

	for i in $HOME/bin/$dir/*; do
		source $i
	done
done

[[ $TERM =~ ^(xterm|vt100|linux)$ ]] && bind Space:magic-space

[ -f ~/.bash_prompt ] && source ~/.bash_prompt
[ -f ~/.extra       ] && source ~/.extra

