[ -f ~/.bash_config ] && source ~/.bash_config

umask 0022

unset MAILCHECK

shopt -s cdspell
shopt -s extglob
shopt -s histappend
shopt -s histreedit
shopt -s histverify
shopt -s progcomp

unalias -a
for dir in env function complete alias; do
	[ -d $HOME/.dot/bash/$dir/ ] || continue;

	for i in $HOME/.dot/bash/$dir/*; do
		source $i
	done
done

[ -n "$PS1" ] && bind Space:magic-space

[[ $TERM =~ ^xterm ]] && export TERM=xterm-direct

[ -f ~/.bash_prompt ] && source ~/.bash_prompt
[ -f ~/.extra       ] && source ~/.extra

