unalias -a

alias !="history2"
alias bc="bc -q"
alias bzip2="_compress /usr/bin/bzip2"
#alias cd="cd >& /dev/null"
alias date2='date "+%n  %R  %A %-d %B%n"'
alias df="df_"
alias diff="diff -x CVS -x .svn -x tags -x .git"
alias ftp="lftp"
alias eog="_wrapdot /usr/bin/eog"
alias jobs="jobs -l"
alias keep="export IGNOREEOF=999"
alias killall="killall -I"
alias l1="/bin/ls --group-directories-first -1"
alias la="/bin/ls --group-directories-first -la -T 0 --color=auto"
alias lc="/bin/ls --group-directories-first -CL -T 0 --color=auto"
alias li="/bin/ls --group-directories-first -gG -lL -T 0 --color=auto -I .\*swp -I \*.[cho] -I lost+found"
alias ll="/bin/ls --group-directories-first -l -T 0 --color=auto"
alias ls="/bin/ls --group-directories-first -gG -lL -T 0 --color=auto -I .\*swp -I lost+found"
alias man="_wrapsimple /usr/bin/man"
alias mkdir="mkdir -p"
alias more="less"
alias nautilus="_wrapdot /usr/bin/nautilus"
alias od="LANG=C hexdump -f ~/.format"
alias odw="LANG=C hexdump -f ~/.format2"
alias rar="unrar"
alias ssh="ssh -q"
alias tar="_wrapsimple /bin/tar"
alias tree="tree -C"
alias vi="vim -X"
alias xz="_compress /usr/bin/xz"

alias  fff="find . -type f                   -print0 | xargs -r -0"
alias  ffd="find . -type d                   -print0 | xargs -r -0"
alias  ffl="find . -type l                   -print0 | xargs -r -0"
alias  ffc="find . -type f  -name \*.c       -print0 | xargs -r -0"
alias  ffh="find . -type f  -name \*.h       -print0 | xargs -r -0"
alias ffch="find . -type f  -name \*.[ch]    -print0 | xargs -r -0"
alias  ffm="find . -type f -iname Makefile\* -print0 | xargs -r -0"
alias  ffp="find . -type f  -name \*.php     -print0 | xargs -r -0"

