#!/bin/bash

MNT=$HOME/derwent
HOST=derwent.arafel.org.uk

if [ -d $MNT ]; then
	if [ -d $MNT/www ]; then
		fusermount -u $MNT
	fi
	rmdir --ignore-fail-on-non-empty $MNT
else
	mkdir -p $MNT
	sshfs $HOST: $MNT
fi

