#!/bin/bash

ICON="/usr/share/icons/hicolor/48x48/apps/typing-monitor.png"
LAST_PLAY=$(stat -c %Y $0)
TIME_NOW=$(date "+%s")
WAIT_TIME=$((3600 * 12)) # hours

ELAPSED=$(($TIME_NOW-$LAST_PLAY))

if [ $ELAPSED -lt $WAIT_TIME ]; then
	notify-send -i $ICON Puzzles "Too soon"
	exit 1
fi

exec 2> /dev/null	# Turn off stderr
touch $0

puzzle-filling  17x13 &
puzzle-galaxies 15x15 &
puzzle-keen     6x6   &
puzzle-loopy    10x10 &
puzzle-map      30x20 &
puzzle-rect     11x11 &
puzzle-signpost 7x7   &
puzzle-singles  8x8   &
puzzle-tents    15x15 &
puzzle-towers   6x6   &

sleep 1.5

for i in Galaxies Loopy Tents Keen Towers Signpost Singles Rectangles Filling Map; do
	wmctrl -r $i -e 0,0,0,1920,1080
	#wmctrl -r $i -b add,fullscreen
	wmctrl -a $i
done
